[project]
name = "sales-assisant-deepagent"
version = "0.1.0"
description = ""
authors = [
    {name = "Mariano-SI",email = "mariano.silva@ufvjm.edu.br"}
]
requires-python = ">=3.12,<4.0"
dependencies = [
    "deepagents (>=0.7.14,<0.8.0)",
    "langchain-mcp-adapters (>=0.3.2,<0.4.0)",
    "langchain-quickjs (>=0.3.7,<0.4.0)",
    "mcp (>=1.24.0,<2.0.0)",
    "langgraph (>=1.2.11,<2.0.0)",
    "langgraph-cli[inmem] (>=0.4.31,<0.5.0)",
    "colorama (>=0.4.6,<0.5.0)",
    "langchain-openai (>=1.6.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"